### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amirouche** [amirouche/qadom#1]
- :eyes: Privacy
  - [ ] Use key exchange to secure point to point communication
- :lock: Security
  - [ ] Add blacklist for misbehaving nodes
  - [ ] Simulate attacks
  - [ ] Secure STORE RPC
  - [ ] Secure FIND_VALUE local method
- :bullettrain_side: Performance
  - [ ] add NAT traversal
  - [ ] add WebSocket for file transfer
- :bug: Features
  - [ ] namespace
  - [ ] realtime pubsub
  - [ ] on-disk persistence via [hoply](https://github.com/amirouche/hoply/)
  - [ ] mark bootstrap nodes
